# Generated by Django 4.2.15 on 2024-08-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_instructor_created_at_instructor_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="parent_contact",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
