services:
  web:
    build: .
    command: poetry run python manage.py runserver 0.0.0.0:8000
    container_name: student-management-system-web
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    container_name: student-management-system-database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=superadmin
      - POSTGRES_DB=student-management-system

volumes:
  postgres_data:
