# Generated by Django 4.2.15 on 2024-08-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendances", "0004_alter_attendance_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="remarks",
            field=models.CharField(blank=True, default=""),
        ),
    ]
