# Generated by Django 4.2.15 on 2024-08-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendances", "0005_alter_attendance_remarks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="remarks",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
