# Generated by Django 4.2.15 on 2024-08-14 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("academics", "0002_initial"),
        ("users", "0001_initial"),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_enrollments",
                to="users.student",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="courses",
                to="academics.program",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="class_instructor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="classes",
                to="users.instructor",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="academics.semester",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="students",
            field=models.ManyToManyField(
                through="courses.Enrollment", to="users.student"
            ),
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.UniqueConstraint(
                fields=("student", "class_instance"),
                name="unique_student_class_enrollment",
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["slug"], name="slug_idx"),
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.UniqueConstraint(
                fields=("name", "program"), name="unique_course_in_program"
            ),
        ),
        migrations.AddConstraint(
            model_name="class",
            constraint=models.UniqueConstraint(
                fields=("section", "course"), name="unique_section_course"
            ),
        ),
    ]
