# Generated by Django 4.2.15 on 2024-08-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
