# Generated by Django 4.2.15 on 2024-08-14 09:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        help_text="Enter the academic year in the format 'YYYY-YYYY'",
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.CharField(max_length=100, unique=True)),
                (
                    "code",
                    models.CharField(
                        help_text="USE 'DEP' prefix.", max_length=10, unique=True
                    ),
                ),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("FALL", "Fall"),
                            ("SPRING", "Spring"),
                            ("SUMMER", "Summer"),
                            ("WINTER", "Winter"),
                        ],
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semesters",
                        to="academics.academicyear",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.CharField(max_length=100, unique=True)),
                (
                    "code",
                    models.CharField(
                        help_text="USE 'PROG' prefix.", max_length=10, unique=True
                    ),
                ),
                ("description", models.TextField()),
                (
                    "duration_years",
                    models.PositiveIntegerField(
                        help_text="Enter the number of years required to complete this program."
                    ),
                ),
                (
                    "degree_type",
                    models.CharField(
                        choices=[
                            ("B.Sc.", "Bachelor of Science"),
                            ("B.A.", "Bachelor of Arts"),
                            ("B.Eng.", "Bachelor of Engineering"),
                            ("M.Sc.", "Master of Science"),
                            ("M.A.", "Master of Arts"),
                            ("M.Eng.", "Master of Engineering"),
                            ("MBA", "Master of Business Administration"),
                            ("BBA", "Bachelor of Business Administration"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "total_credits",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(300)]
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="programs",
                        to="academics.department",
                    ),
                ),
            ],
        ),
    ]
