# Generated by Django 4.2.15 on 2024-08-14 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("academics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="head_of_department",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="department_head",
                to="users.instructor",
            ),
        ),
        migrations.AddConstraint(
            model_name="academicyear",
            constraint=models.UniqueConstraint(
                fields=("start_date", "end_date"), name="unique_academic_year_dates"
            ),
        ),
    ]
