# Generated by Django 4.2.15 on 2024-08-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0002_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="semester",
            constraint=models.UniqueConstraint(
                fields=("name", "start_date", "end_date", "academic_year"),
                name="unique_semester",
            ),
        ),
    ]
