# Generated by Django 4.2.15 on 2024-08-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0003_semester_unique_semester"),
    ]

    operations = [
        migrations.AddField(
            model_name="semester",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
