# Generated by Django 4.2.15 on 2024-08-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0004_semester_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="semester",
            name="is_active",
        ),
        migrations.AddField(
            model_name="semester",
            name="status",
            field=models.CharField(
                choices=[("ACT", "Active"), ("COMP", "Completed"), ("ARC", "Archived")],
                default="ACT",
                max_length=5,
            ),
        ),
    ]
