# Generated by Django 4.2.15 on 2024-08-31 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0005_remove_semester_is_active_semester_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="code",
            field=models.CharField(
                help_text="Use 'DEP' prefix.", max_length=10, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="duration_years",
            field=models.PositiveIntegerField(
                help_text="Enter the number of years required to complete this program.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(6),
                ],
            ),
        ),
    ]
